### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by maniast** [NVIDIA-Omniverse/IsaacGymEnvs#45]
I keep getting this at random time periods during my training. The specific error: 

/buildAgent/work/45f70df4210b2e3e/source/gpunarrowphase/src/PxgNarrowphaseCore.cpp (9908) : internal error : GPU compressContactStage1 fail to launch kernel stage 1!!

/buildAgent/work/45f70df4210b2e3e/source/gpunarrowphase/src/PxgNarrowphaseCore.cpp (9945) : internal error : GPU compressContactStage2 fail to launch kernel stage 1!!

**Comment by yilin-wu98** [comment]
I may have encountered a similar issue. Have you found any way to solve it? Which task are you training?

**Comment by MyelinsheathXD** [comment]
having the same issue. Can run AMP samples

some common errors

`ed: ../../../source/plugins/carb/gym/impl/Gym/GymPhysX.cpp: 5993
[Error] [carb.gym.plugin] Gym cuda error: an illegal memory access was encountered: ../../../source/plugins/carb/gym/impl/Gym/GymPhysXCuda.cu: 937
[Error] [carb.gym.plugin] Failed to fill root state tenso`

**Comment by MyelinsheathXD** [comment]
Solution is to decrease batch size , contact nums, env_nums.
Since these vatiables' memory allocation  consuming required pytorch's memory allocation

**Comment by explore-code-world7** [comment]
I find the problem in a while circle. 
![image](https://github.com/isaac-sim/IsaacGymEnvs/assets/174762625/2c70e41d-a282-4269-8560-6bea61332085)

So I stopped the circle after first implement,then I got another previous error:
![image](https://github.com/isaac-sim/IsaacGymEnvs/assets/174762625/a3bf6539-8b22-4be3-b65d-1e78acccb2a1)
This is caused by implement`gym.simulate(sim)` before `gym.prepare_sim(sim)`，I added it before the while circle containing
`gym.simulate(sim)`，the problem was resolved
